INSERT INTO TYPE (NAME) VALUES ('MUSIC');
INSERT INTO TYPE (NAME) VALUES ('ART');
INSERT INTO TYPE (NAME) VALUES ('CULTURE');
INSERT INTO TYPE (NAME) VALUES ('COMEDY');
INSERT INTO TYPE (NAME) VALUES ('BAR');
INSERT INTO TYPE (NAME) VALUES ('CLUB');
INSERT INTO TYPE (NAME) VALUES ('PARK');
INSERT INTO TYPE (NAME) VALUES ('LAKE');

INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('New Pictures: Amar Kanwar, Such a Morning', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('Jason Moran', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('Voile/Toile – Toile/Voile', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('Gudrun Sjoden: A Colourful Universe', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('A Fistful of Spaghetti Westerns', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('Somalis + Minnesota', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('Beth Dow: Prediction Error', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('Minnesota Fringe Festival 2018', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('Origami in the Garden', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('Wallpaper: an altered book experiment', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('Skyline Mini Golf', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('Mill City Night Market', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('Formation: A Juried Exhibition of the Guild of Book Workers', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('Hot Dish Happy Hour', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('Hand to God', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('The Legend of Georgia McBride', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('West Side Story', 'description');
INSERT INTO EVENT (NAME, DESCRIPTION) VALUES ('International Reggae All-Stars', 'description');


INSERT INTO EVENT_TYPE (EVENT_ID, TYPE_ID) VALUES (1, 1);
INSERT INTO EVENT_TYPE (EVENT_ID, TYPE_ID) VALUES (2, 2);
INSERT INTO EVENT_TYPE (EVENT_ID, TYPE_ID) VALUES (3, 3);
INSERT INTO EVENT_TYPE (EVENT_ID, TYPE_ID) VALUES (4, 4);
INSERT INTO EVENT_TYPE (EVENT_ID, TYPE_ID) VALUES (5, 1);
INSERT INTO EVENT_TYPE (EVENT_ID, TYPE_ID) VALUES (6, 2);
INSERT INTO EVENT_TYPE (EVENT_ID, TYPE_ID) VALUES (7, 3);
INSERT INTO EVENT_TYPE (EVENT_ID, TYPE_ID) VALUES (8, 4);
INSERT INTO EVENT_TYPE (EVENT_ID, TYPE_ID) VALUES (9, 1);
INSERT INTO EVENT_TYPE (EVENT_ID, TYPE_ID) VALUES (10, 2);
INSERT INTO EVENT_TYPE (EVENT_ID, TYPE_ID) VALUES (11, 3);
INSERT INTO EVENT_TYPE (EVENT_ID, TYPE_ID) VALUES (12, 4);
INSERT INTO EVENT_TYPE (EVENT_ID, TYPE_ID) VALUES (13, 5);
--EVENT_CLASSIFICATION EVENT_TYPE_HIERARCHY

